### ISSUE TITLE
Apple silicon ARM chip support

### ISSUE THREAD

**Issue by zac1st1k** [clj-commons/byte-transforms#8]
I got an error on latest M1 MacBook

`[FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64"`

It seems caused by incompatible dependency `snappy`.

https://github.com/xerial/snappy-java/blob/master/Milestone.md#snappy-java-1182-2020-11-28

I will create a PR for it.

Cheers

**Comment by KingMob** [comment]
Fixed by #9
